// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github/kunhou/simple-backend/deliver/http/controller"
	"github/kunhou/simple-backend/deliver/http/router"
	"github/kunhou/simple-backend/deliver/http/server"
	"github/kunhou/simple-backend/pkg/config"
	"github/kunhou/simple-backend/pkg/data"
	"github/kunhou/simple-backend/pkg/servmanager"
	"github/kunhou/simple-backend/repository/setting"
	setting2 "github/kunhou/simple-backend/usecase/setting"
)

// Injectors from wire.go:

// initApplication init application.
func initApplication(debug bool, serverConf *config.Server, dbConf *data.DatabaseConf) (*servmanager.Application, func(), error) {
	db := data.NewDB(debug, dbConf)
	iSettingRepository := setting.NewSettingRepo(db)
	settingUsecase := setting2.NewSettingUsecase(iSettingRepository)
	settingController := controller.NewSettingController(settingUsecase)
	settingRouter := router.NewSettingRouter(settingController)
	engine := server.NewHTTPServer(debug, settingRouter)
	application := newApplication(serverConf, engine)
	return application, func() {
	}, nil
}
